export const APP_VERSION = "1.0.0";

const field = (id, label, options = [], extra = {}) => ({ id, label, options, type: "select", ...extra });
const text = (id, label, placeholder = "", extra = {}) => field(id, label, [], { type: "text", placeholder, ...extra });
const multi = (id, label, options, extra = {}) => field(id, label, options, { type: "multi", ...extra });

export const shared = {
  skin: ["Porcelain","Fair","Light","Light Medium","Medium","Golden Brown","Caramel","Warm Brown","Deep Brown","Rich Deep","Ebony","Custom Natural Skin Tone"],
  eyes: ["Dark Brown","Warm Brown","Hazel","Amber","Green","Blue","Gray","Custom Natural Eye Color"],
  textures: ["Straight","Wavy","Curly","Coily","Kinky","Locs","Braids","Twists","Silk Pressed","Bald","Shaved","Custom"],
  hair: ["Afro","Tapered Afro","High Puff","Two Puffs","Ponytail","Low Ponytail","Pigtails","Bun","Curly Updo","Braided Updo","Box Braids","Knotless Braids","Cornrows","Locs","Bob","Pixie","Long Layers","Waves","Defined Curls","Half Up Half Down","Protective Style","Mohawk","Fade","Low Cut","Shaved Head","Custom"],
  hairColors: ["Black","Soft Black","Dark Brown","Brown","Auburn","Copper","Blonde","Platinum","Gray","White","Burgundy","Pink","Purple","Blue","Green","Rainbow","Ombre","Custom"],
  palette: ["Black, Champagne Gold, and Ivory","Plum, Rose Gold, and Cream","Berry Pink, Lilac, Sky Blue, and Lemon","Deep Navy, Ocean Blue, Seafoam, and White","Forest Green, Clay, Sand, and Cream","Burgundy, Gold, Black, and Ivory","Mocha, Dusty Rose, Sage, and Cream","Rainbow Pastels","Jewel Tones","Earth Tones","Monochrome","Custom"],
  quality: ["Premium detail","Crisp edges","Professional finish","Commercial quality","Small-size readability","Balanced composition","Rich color harmony","Clean anatomy","High visual clarity","Production-ready rendering"]
};

const characterSteps = [
  field("presentation","Gender Presentation",["Woman","Man","Nonbinary Adult","Androgynous Adult","Feminine Presentation","Masculine Presentation","Custom Adult Presentation"],{required:true}),
  field("age","Adult Age Group",["Young Adult","Adult","Middle-Aged Adult","Mature Adult","Senior Adult"],{required:true}),
  field("role","Adult Role",["Entrepreneur","Executive","Creative Professional","Artist","Author","Designer","Teacher","Professor","Scientist","Healthcare Professional","Attorney","Chef","Musician","Athlete","Influencer","Parent","Grandparent","Community Leader","Faith Leader","Fashion Model","Office Professional","Small Business Owner","Homemaker","Retired Professional","Custom"]),
  field("body","Body and Proportions",["Petite","Slim","Average Build","Athletic","Curvy","Plus Size","Muscular","Broad","Soft Build","Stocky","Tall and Lean","Custom"]),
  field("skin","Skin and Complexion",shared.skin,{required:true}),
  field("face","Face Shape",["Round","Oval","Heart","Square","Diamond","Oblong","Soft Angular","Full","Narrow","Custom"]),
  field("eyes","Eyes",["Round","Almond","Monolid","Hooded","Upturned","Downturned","Wide Set","Deep Set","Large Expressive","Custom"]),
  field("eyeColor","Eye Color",shared.eyes),
  field("hairTexture","Hair Texture",shared.textures,{required:true}),
  field("hairStyle","Hair Style",shared.hair,{required:true}),
  field("hairColor","Hair Color",shared.hairColors),
  field("grooming","Makeup and Grooming",["None","Natural","Soft Glam","Full Glam","Editorial","Luxury","Colorful","Gothic","Bridal","Stage","Mature Glam","Clean Shaven","Light Stubble","Short Beard","Full Beard","Custom"]),
  field("clothing","Realistic Adult Clothing",["Everyday Casual","Smart Casual","Business Casual","Professional Workwear","Formal Wear","Church Clothing","Wedding Guest Clothing","Bridal Wear","Groom Attire","Athletic Wear","Loungewear","Pajamas","Seasonal Clothing","Vacation Clothing","Date-Night Clothing","Streetwear","Denim Clothing","Modest Clothing","Contemporary Fashion","Mature Fashion","Nyvera Luxury Clothing Line","Custom Realistic Clothing"],{required:true}),
  field("outfit","Outfit",["Blouse and Tailored Pants","Button-Down Shirt and Trousers","Casual Dress","Cocktail Dress","Evening Dress","Jumpsuit","Pantsuit","Business Suit","Wedding Dress","Church Dress","Tracksuit","Pajama Set","Custom Realistic Outfit"]),
  field("shoes","Shoes",["Sneakers","Boots","Heels","Flats","Sandals","Loafers","Formal Shoes","Designer-Inspired Heels","Fashion Boots","Athletic Shoes","Slippers","Barefoot","Custom"]),
  multi("accessories","Accessories",["Handbag","Tote Bag","Briefcase","Backpack","Glasses","Sunglasses","Hat","Scarf","Belt","Gloves","Book","Microphone","Laptop","Tablet","Camera","Art Supplies","Coffee Mug","Phone","Umbrella"]),
  multi("jewelry","Jewelry",["None","Stud Earrings","Hoop Earrings","Diamond Earrings","Pearl Earrings","Necklace","Layered Necklaces","Choker","Bracelets","Bangles","Rings","Watch","Brooch"]),
  field("expression","Expression",["Happy","Joyful","Confident","Calm","Relaxed","Serious","Determined","Mysterious","Playful","Surprised","Curious","Powerful","Gentle","Thoughtful","Custom"]),
  field("pose","Pose",["Standing","Walking","Sitting","Running","Dancing","Fashion Pose","Power Pose","Hands on Hips","Holding an Object","Reading","Working","Speaking","Portrait Pose","Editorial Pose","Custom"]),
  field("environment","Environment",["Transparent Background","Professional Studio","Luxury Interior","Bedroom","Home Office","Corporate Office","Classroom","Library","City","Nature","Garden","Forest","Beach","Elegant Home","Restaurant","Stage","Runway","Café","Church","Creative Studio","Vacation Resort","Custom"],{required:true}),
  field("lighting","Lighting",["Soft Daylight","Golden Hour","Dreamy Glow","Cinematic","Studio Lighting","Rim Lighting","Neon","Candlelight","Moonlight","High Fashion Lighting","Window Light","Softbox Lighting","Custom"]),
  field("palette","Color Palette",shared.palette),
  field("artStyle","Art Style",["Semi-Realistic","Realistic","Luxury Chibi","Classic Chibi","Soft 3D","Kawaii","Storybook","Editorial Illustration","Fashion Illustration","Anime-Inspired","Cartoon","Watercolor","Digital Painting","Plush Style","Clay Style","Comic Style","Custom"],{required:true}),
  field("composition","Composition",["Full Body","Three-Quarter Body","Half Body","Portrait","Close-Up","Character Sheet","Turnaround Sheet","Expression Sheet","Fashion Lineup","Couple Composition","Adult Group Composition","Custom"]),
  multi("quality","Rendering Quality",shared.quality),
  multi("negative","Negative Guidance",["distorted hands","extra fingers","blurry eyes","cropped character","duplicate accessories","warped facial features","unreadable text","low detail","muddy colors","cluttered background","malformed anatomy","duplicate people","fantasy features","costume clothing"]),
  text("customDetails","Custom Details","Add any final custom details.",{type:"textarea"})
];

const kidsSteps = [
  field("age","Child Age Group",["Baby","Toddler","Preschool Child","Young Child","Older Child","Tween","Teen"],{required:true}),
  field("presentation","Gender Presentation",["Girl","Boy","Nonbinary Child","Androgynous Child","Feminine Presentation","Masculine Presentation","Custom Child Presentation"],{required:true}),
  field("role","Everyday Role",["Student","Reader","Young Artist","Young Scientist","Young Musician","Young Athlete","Young Cook","Young Coder","Young Entrepreneur","Helper","Big Sibling","Little Sibling","Birthday Child","Bedtime Child","Church Child","School Leader","Class Helper","Book Lover","Nature Explorer","Vacation Child","Family Photo Child","Creative Child","Custom Realistic Role"]),
  field("build","Age-Appropriate Build",["Baby Build","Toddler Build","Small for Age","Average for Age","Tall for Age","Petite","Slim","Average","Soft Build","Athletic","Stocky","Tall and Lean","Custom Age-Appropriate Build"]),
  field("skin","Skin and Complexion",shared.skin,{required:true}),
  field("face","Face Shape",["Round","Oval","Heart","Square","Soft Angular","Full","Narrow","Custom"]),
  field("eyeColor","Eye Color",shared.eyes),
  field("hairTexture","Hair Texture",shared.textures),
  field("hairStyle","Hair Style",[...shared.hair,"Baby Curls","Toddler Puffs"]),
  field("hairColor","Hair Color",shared.hairColors),
  field("grooming","Child Grooming",["Natural","Fresh-Faced","Moisturized Skin","Light Lip Balm","Neat Grooming","No Makeup","Natural Makeup (Teen Only)","Light Age-Appropriate Makeup (Teen Only)","Custom"]),
  field("clothing","Realistic Clothing",["Everyday Casual","School Clothing","School Uniform","Church Clothing","Birthday Outfit","Holiday Clothing","Seasonal Clothing","Sportswear","Activewear","Pajamas","Loungewear","Formal Clothing","Wedding Guest Clothing","Family Photo Clothing","Vacation Clothing","Play Clothing","Rainwear","Winter Clothing","Summer Clothing","Modest Clothing","Contemporary Kids Fashion","Tween Fashion","Teen Fashion","Nyvera Kids Luxury Clothing Line","Custom Age-Appropriate Clothing"],{required:true}),
  field("shoes","Shoes",["Sneakers","School Shoes","Loafers","Flats","Sandals","Boots","Rain Boots","Athletic Shoes","Dress Shoes","Slippers","Baby Shoes","Toddler Shoes","Luxury Sneakers","Barefoot","Custom"]),
  multi("accessories","Accessories",["Backpack","School Bag","Lunchbox","Glasses","Sunglasses","Hat","Scarf","Book","Notebook","Pencil","Crayons","Art Supplies","Tablet","Toy","Stuffed Animal","Water Bottle","Sports Ball","Musical Instrument","Headphones","Hair Accessories","Age-Appropriate Jewelry"]),
  field("expression","Expression",["Happy","Joyful","Excited","Calm","Sleepy","Curious","Proud","Confident","Shy","Thoughtful","Surprised","Playful","Focused","Gentle","Custom"]),
  field("pose","Pose",["Standing","Walking","Sitting","Running","Dancing","Reading","Drawing","Writing","Studying","Playing","Holding an Object","Waving","School Portrait Pose","Family Photo Pose","Sports Pose","Bedtime Pose","Baby Sitting Pose","Toddler Walking Pose","Custom"]),
  multi("supportingPeople","Supporting People",["Mother","Father","Parent","Grandmother","Grandfather","Grandparent","Adult Caregiver","Teacher","Classroom Assistant","Older Sibling","Younger Sibling","Friend","Classmate"]),
  field("environment","Environment",["Transparent Background","Studio","Bedroom","Nursery","Playroom","Living Room","Kitchen","Classroom","School Hallway","School Library","Public Library","Playground","Park","Garden","Backyard","Church","Birthday Party","Family Gathering","Sports Field","Gym","Beach","Vacation Setting","Doctor’s Office","Daycare","Art Room","Music Room","Science Classroom","Custom"],{required:true}),
  field("lighting","Lighting",["Soft Daylight","Window Light","Golden Hour","Bright Classroom Light","Cozy Bedtime Glow","Studio Lighting","Soft Pastel Glow","Warm Home Lighting","Outdoor Daylight","Gentle Rim Light","Custom"]),
  field("palette","Color Palette",["Berry Pink, Lilac, Sky Blue, and Lemon","Baby Pink, Powder Blue, Cream, and Sage","Deep Navy, Sky Blue, White, and Gold","Forest Green, Clay, Sand, and Cream","Mocha, Dusty Rose, Sage, and Cream","Red, Navy, White, and Gold","Rainbow Pastels","Bright Primary Colors","Soft Neutrals","School Colors","Autumn Warmth","Winter Blues","Spring Pastels","Summer Brights","Custom"]),
  field("artStyle","Art Style",["Semi-Realistic Children’s Illustration","Realistic","Classic Chibi","Luxury Chibi","Kawaii","Soft 3D","Storybook","Watercolor","Plush","Clay","Cartoon","Playful Editorial","Coloring Book Line Art","Digital Painting","Custom"],{required:true}),
  field("composition","Composition",["Full Body","Three-Quarter Body","Half Body","Portrait","Close-Up","Child Character Sheet","Expression Sheet","Outfit Sheet","Family Composition","Classroom Composition","Sibling Composition","Custom"]),
  multi("negative","Negative Guidance",["distorted hands","extra fingers","blurry eyes","cropped child","duplicate children","identical faces","warped facial features","malformed anatomy","adult body proportions","adult glamour","revealing clothing","fantasy features","superhero clothing","costume clothing","unsafe objects","unreadable text","cluttered background","low detail","muddy colors"]),
  text("customDetails","Custom Details","Add any final custom details.",{type:"textarea"})
];

// Keep legacy/specialized Kids builders aligned with the same wholesome UI.
const safeKidsField=id=>kidsSteps.find(item=>item.id===id);
Object.assign(safeKidsField("role"),{options:["Student","Reader","Young Artist","Young Scientist","Young Musician","Young Athlete","Young Cook","Young Coder","Young Entrepreneur","Helper","Big Sibling","Little Sibling","Birthday Child","Bedtime Child","Church Child","School Leader","Class Helper","Book Lover","Nature Explorer","Vacation Child","Family Photo Child","Creative Child","Positive Everyday Interest"]});
Object.assign(safeKidsField("build"),{label:"Age-Appropriate Proportions",options:["Natural Age-Appropriate Build","Baby Build","Toddler Build","Realistic Child Proportions","Classic Chibi Proportions","Soft Storybook Proportions","Age-Appropriate Build"]});
Object.assign(safeKidsField("grooming"),{label:"Natural Grooming",options:["Simple Natural Presentation","Fresh-Faced","Neat Age-Appropriate Grooming","School-Appropriate Grooming","Supervised Stage Presentation (Teen Only)","Custom Age-Appropriate Grooming"]});
Object.assign(safeKidsField("clothing"),{options:["Everyday Playwear","School Clothing","Sportswear","Church Clothing","Pajamas","Seasonal Clothing","Birthday Clothing","Graduation Clothing","Family Photo Clothing","Casual Tween Clothing","Teen School Fashion","Nyvera Kids Luxury Clothing Line","Custom Age-Appropriate Clothing"]});
Object.assign(safeKidsField("accessories"),{options:["Backpack","Lunchbox","Books","Notebook","Pencil","Crayons","Markers","Tablet","Laptop","Headphones","Glasses","Water Bottle","Sports Ball","Art Supplies","Science Kit","Camera","Musical Instrument","Plush Toy","Hair Bows","Headband","School Bag","Graduation Cap","Simple Child-Safe Jewelry"]});
Object.assign(safeKidsField("expression"),{label:"Wholesome Expression",options:["Happy","Joyful","Curious","Proud","Excited","Thoughtful","Focused","Friendly","Calm","Brave","Confident","Determined","Surprised","Laughing","Kind","Hopeful","Creative","Peaceful","Encouraged","Caring","Playful Smile","Cheerful Confidence","Fun Personality","Custom Wholesome Expression"]});
Object.assign(safeKidsField("pose"),{label:"Safe Activity Pose",options:["Standing","Sitting","Reading","Drawing","Writing","Studying","Holding Books","Carrying Backpack","Waving","Laughing","Playing","Running","Dancing","Sports Pose","Classroom Pose","School Picture Pose","Graduation Pose","Art Activity Pose","Music Practice Pose","Science Project Pose","Family Photo Pose","Casual Locker Pose","Sitting at Desk","Studying at Table","Custom Safe Pose"]});
Object.assign(safeKidsField("environment"),{options:["Transparent Background","Studio","Classroom","Library","Homeschool Workspace","School Hallway","School Locker Area","Art Room","Music Room","Science Lab","Reading Corner","Bedroom","Playroom","Family Living Room","Kitchen With Family","Park","Playground","Garden","Beach","Zoo","Aquarium","Museum","Bookstore","Sports Field","Gymnasium","Church Classroom","Youth Group Room","Graduation Stage","Birthday Party","Camping Site","Bright Family-Friendly Studio","Custom Safe Scene"]});
Object.assign(safeKidsField("negative"),{options:["distorted anatomy","extra fingers","missing fingers","blurry eyes","duplicate characters","inconsistent identity","changed skin tone","changed hairstyle","incorrect age group","cropped character","cropped product","warped layout","unreadable text","misspelled text","incorrect dimensions","incorrect item count","cluttered composition","unrelated objects","unsafe objects","mature styling","fantasy elements","superhero elements","weapons","logos","brand names","wordmarks","signatures","watermarks","monograms","standalone letter N symbols"]});

const stickerSteps = [
  text("title","Sticker Product Title","Name this sticker product",{required:true}),
  field("productType","Product Format",["Single Sticker","Sticker Sheet","Sticker Pack","Phrase Collection","Icon Collection","Object Collection","Decorative Collection","Digital Planner Collection","Sticker Mockup","Product Packaging"],{required:true}),
  field("style","Sticker Style",["Classic Chibi","Luxury Chibi","Semi-Realistic","Realistic","Kawaii","Soft 3D","Storybook","Editorial","Fashion Illustration","Watercolor","Plush","Clay","Cartoon","Comic","Minimal","Flat Vector","Hand-Drawn","Doodle","Holographic","Glitter","Metallic","Vinyl","Paper-Cut","Embroidered Patch","Puffy Sticker","Retro","Vintage","Y2K","Bohemian","Cottagecore","Faith-Inspired","Luxury","Playful","Custom"],{required:true}),
  multi("subjects","Subject Categories",["Human Figures","Fashion","Beauty","Hair","Accessories","Faith Symbols","Inspirational Phrases","Funny Phrases","School Supplies","Planner Icons","Business Icons","Office Objects","Food and Drinks","Self-Care Objects","Home and Lifestyle","Travel","Weather","Flowers","Plants","Celestial Objects","Seasonal Objects","Holiday Objects","Decorative Shapes","Abstract Designs"]),
  text("theme","Theme","e.g. cozy reading, back to school",{required:true}),
  field("count","Exact Sticker Count",["1","6","8","10","12","15","18","20","22","24","25","28","29","30","31","32","Custom"],{required:true}),
  text("phraseCount","Phrase Sticker Count","0",{inputMode:"numeric"}),text("iconCount","Icon Sticker Count","0",{inputMode:"numeric"}),text("objectCount","Object Sticker Count","0",{inputMode:"numeric"}),text("decorativeCount","Decorative Sticker Count","0",{inputMode:"numeric"}),text("humanCount","Human-Figure Sticker Count","0",{inputMode:"numeric"}),
  text("exactText","Exact Text or Phrases","Preserve spelling and punctuation",{type:"textarea"}),
  text("objectList","Exact Object List","Comma-separated exact objects",{type:"textarea"}),
  field("sheetSize","Sheet or Product Size",["8.5 × 11 inches","8 × 10 inches","A4","A5","12 × 12 inches","Digital Canvas","Custom"]),
  field("orientation","Orientation",["Portrait","Landscape","Square","Custom"]),
  field("palette","Palette",shared.palette),
  field("border","Border",["White Die-Cut Border","Colored Border","Gold Border","Holographic Border","Black Border","No Border","Custom"],{required:true}),
  field("finish","Finish",["Matte","Glossy","Holographic","Glitter","Metallic","Transparent","Soft 3D","Vinyl","Puffy","Custom"],{required:true}),
  field("background","Background",["Transparent Background","White Sheet","Colored Sheet","Themed Background","Retail Mockup Background","Custom"]),
  field("layout","Layout",["Balanced Grid","Loose Scatter","Dense Sheet","Separate Rows","Inventory Grid","Retail Presentation","Custom"]),
  field("useType","Product Use",["Digital Download","Printable Sticker Sheet","Physical Sticker Pack","Mockup Only"]),
  multi("negative","Negative Guidance",["overlapping stickers","duplicate stickers","cropped stickers","incomplete subjects","blurry edges","uneven die-cut borders","muddy colors","cluttered sheet layout","misspelled text","extra objects","incorrect sticker count","low detail","inconsistent style","malformed human figures","accidental background boxes","unrelated products in mockups"]),
  text("customDetails","Custom Details","Add packaging, audience, or presentation details.",{type:"textarea"})
];

const characterBuilders = ["Full Character Builder","Quick Character Builder","Face Builder","Hair Builder","Fashion Builder","Portrait Builder","Professional Character Builder","Editorial Character Builder","Couple Builder","Adult Family Builder","Adult Group Builder","Avatar Builder","Character Sheet Builder"];
const kidsBuilders = ["Kids Character Builder","Baby Character Builder","Toddler Character Builder","School Character Builder","Teen Character Builder","Family Scene Builder","Classroom Scene Builder","Children’s Book Builder","Story Scene Builder","Coloring Page Builder","Activity Sheet Builder","Educational Printable Builder","School Supply Design Builder","Kids Wallpaper Builder","Affirmation Card Builder","Bookmark Builder","Kids Product Mockup Builder"];
const stickerBuilders = ["Single Sticker Builder","Sticker Sheet Builder","Sticker Pack Builder","Phrase Sticker Builder","Icon Sticker Builder","Object Sticker Builder","Decorative Sticker Builder","Digital Planner Sticker Builder","Faith Sticker Builder","Seasonal Sticker Builder","Business Sticker Builder","School Sticker Builder","Lifestyle Sticker Builder","Self-Care Sticker Builder","Sticker Mockup Builder","Product Packaging Prompt Builder","Style Explorer"];

const iconFor=name=>name.includes("Face")?"face":name.includes("Hair")?"hair":name.includes("Fashion")||name.includes("Clothing")?"fashion":name.includes("Portrait")||name.includes("Character")||name.includes("Family")||name.includes("Classroom")?"portrait":name.includes("Book")?"book":name.includes("Coloring")?"crayon":name.includes("School")?"school":name.includes("Activity")||name.includes("Printable")||name.includes("Affirmation")||name.includes("Wallpaper")?"activity":name.includes("Sheet")?"sheet":name.includes("Pack")?"pack":name.includes("Phrase")?"phrase":name.includes("Planner")?"planner":name.includes("Mockup")||name.includes("Packaging")?"mockup":name.includes("Style")?"palette":name.includes("Sticker")?"single":"sparkle";
const makeBuilders = names => names.map((name) => ({ id:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""), name, icon:iconFor(name) }));
export const studios = {
  character:{id:"character",name:"Nyvera Character Studio",short:"Character Studio",label:"The Heart of Nyvera",description:"Create original adult human characters from face to fashion.",icon:"character",loading:"Building Your Character Vision...",welcome:"Create Someone Unforgettable",welcomeCopy:"Build every detail. Shape every style. Bring your adult character to life.",builders:makeBuilders(characterBuilders),steps:characterSteps,templates:["Luxury Businesswoman","Confident Entrepreneur","Creative Director","Elegant Author","Faith-Filled Woman","Distinguished Gentleman","Mature Fashion Icon","Cozy Book Lover","Executive Leader","Editorial Model","Contemporary Professional","Senior Style Icon","Church Sunday Elegance","Luxury Brunch Look","Formal Evening Guest"]},
  kids:{id:"kids",name:"Nyvera Kids Studio",short:"Kids Studio",description:"Create human child characters, books, learning products, school designs, and childhood scenes.",icon:"kids",loading:"Big Imaginations Start Here!",welcome:"Create Something Wonderful",welcomeCopy:"Human characters, stories, learning fun, and childhood moments made easy.",builders:makeBuilders(kidsBuilders),steps:kidsSteps,templates:["Kindergarten First Day","Little Scientist","Bedtime Toddler","Young Reader","Faith-Filled Girl","Faith-Filled Boy","Classroom Learning Scene","Family Reading Night","Back-to-School Child","Coloring Book Student","Tween Creative","Teen Future Leader","Alphabet Learning Set","Kindness Poster","School Supply Collection","Premium Birthday Child","Church Sunday Child","Family Photo Outfit","Cozy Winter Baby","Teen School Portrait"]},
  sticker:{id:"sticker",name:"Nyvera Sticker Studio",short:"Sticker Studio",description:"Create single stickers, sheets, packs, phrases, mockups, and themed collections.",icon:"sticker",loading:"Unpacking Your Sticker Magic...",welcome:"Turn Every Idea Into Sticker Magic",welcomeCopy:"Choose a style, build a collection, and create a polished sticker product.",builders:makeBuilders(stickerBuilders),steps:stickerSteps,templates:["Queen Energy Sticker Pack","Faith and Encouragement Sheet","Luxury Self-Care Collection","Back-to-School Sticker Pack","Digital Planner Essentials","Seasonal Celebration Sheet","Small Business Sticker Pack","Teacher Reward Stickers","Luxury Phrase Stickers","Holographic Icon Collection","Cozy Reading Stickers","Beauty and Fashion Collection","Gratitude Sticker Sheet","Motivational Business Pack","Holiday Decorative Collection","Church Encouragement Pack","School Subject Icons","Birthday Sticker Collection","Digital Download Mockup","Luxury Sticker Box Mockup"]}
};

export const defaults = {
  character:{presentation:"Woman",age:"Adult",role:"Creative Professional",body:"Average Build",skin:"Warm Brown",face:"Oval",eyes:"Almond",eyeColor:"Dark Brown",hairTexture:"Curly",hairStyle:"Defined Curls",hairColor:"Dark Brown",grooming:"Natural",clothing:"Smart Casual",outfit:"Blouse and Tailored Pants",shoes:"Loafers",accessories:["Laptop"],jewelry:["Stud Earrings"],expression:"Confident",pose:"Standing",environment:"Professional Studio",lighting:"Soft Daylight",palette:"Plum, Rose Gold, and Cream",artStyle:"Semi-Realistic",composition:"Full Body",quality:["Premium detail","Commercial quality","Clean anatomy"],negative:["distorted hands","extra fingers","fantasy features"]},
  kids:{age:"Young Child",presentation:"Girl",role:"Young Artist",build:"Natural Age-Appropriate Build",skin:"Golden Brown",face:"Round",eyeColor:"Warm Brown",hairTexture:"Coily",hairStyle:"Two Puffs",hairColor:"Black",grooming:"Fresh-Faced",clothing:"Everyday Playwear",shoes:"Sneakers",accessories:["Art Supplies"],expression:"Joyful",pose:"Drawing",supportingPeople:[],environment:"Art Room",lighting:"Soft Daylight",palette:"Berry Pink, Lilac, Sky Blue, and Lemon",artStyle:"Storybook",composition:"Full Body",negative:["incorrect age group","fantasy elements","unsafe objects"]},
  sticker:{title:"Original Sticker Collection",productType:"Sticker Sheet",style:"Holographic",subjects:["Inspirational Phrases","Decorative Shapes"],theme:"creative confidence",count:"12",phraseCount:"6",iconCount:"0",objectCount:"0",decorativeCount:"6",humanCount:"0",exactText:"",objectList:"",sheetSize:"A4",orientation:"Portrait",palette:"Plum, Rose Gold, and Cream",border:"White Die-Cut Border",finish:"Holographic",background:"White Sheet",layout:"Balanced Grid",useType:"Printable Sticker Sheet",negative:["overlapping stickers","duplicate stickers","incorrect sticker count","misspelled text"]}
};

export function fieldsFor(studioId,builderName){
  const all=studios[studioId].steps;
  if(builderName==="Full Character Builder"||builderName==="Kids Character Builder"||studioId==="sticker") return all;
  const common=["presentation","age","role","skin","hairTexture","hairStyle","hairColor","clothing","shoes","expression","pose","environment","lighting","palette","artStyle","composition","negative","customDetails"];
  if(studioId==="character"&&/(Couple|Family|Group)/.test(builderName)) return [...all.filter(x=>common.includes(x.id)),text("peopleCount","Number of Adults","2",{required:true,inputMode:"numeric"}),text("relationships","Relationship or Group Roles","Partners, colleagues, adult siblings...",{required:true}),field("coordination","Clothing Coordination",["Distinct outfits","Coordinated palette","Matching formalwear","Custom"])];
  if(builderName.includes("Book")) return [...all.filter(x=>["age","presentation","skin","hairStyle","clothing","environment","palette","artStyle","customDetails"].includes(x.id)),field("bookType","Book Type",["Board Book","Picture Book","Early Reader","Activity Story","Bedtime Story","Faith-Based Story","Educational Story","School Story","Family Story","Social-Emotional Story","Realistic Adventure Story","Custom"],{required:true}),text("learningGoal","Learning Goal","What should young readers learn?"),text("pageCount","Page Count","24"),text("trimSize","Trim Size","8 × 10 inches"),field("textPlacement","Text Placement",["Top text space","Bottom text space","Alternating text space","Full-bleed with safe text area"]),field("fullStory","Output Scope",["Prompts and outline only","Full Story"] )];
  if(builderName.includes("Coloring")) return [field("age","Age Range",["0–3","3–5","5–7","7–10","10–12","Teen"],{required:true}),text("theme","Theme","Learning, school, family...",{required:true}),field("detailLevel","Detail Level",["Very Simple","Simple","Moderate","Detailed"]),field("pageSize","Page Size",["8.5 × 11 inches","A4","Custom"]),text("customDetails","Custom Details","Printable content",{type:"textarea"})];
  if(builderName.includes("Activity Sheet")) return [field("age","Age Group",["3–5","5–7","7–10","10–12","Teen"],{required:true}),field("activityType","Activity Type",["Maze","Matching Activity","Find the Difference","Word Search","Simple Puzzle","Trace and Draw","Color and Learn","Cut and Paste","Connect the Dots","Emotion Activity","Faith Activity","School Activity","Custom"],{required:true}),field("difficulty","Difficulty",["Easy","Moderate","Challenging"]),text("theme","Theme","School, kindness, seasons..."),text("instructions","Exact Instructions","Instructions shown on the page",{type:"textarea"}),text("itemCount","Number of Items","10",{inputMode:"numeric"}),field("pageSize","Page Size",["8.5 × 11 inches","A4","Custom"]),text("customDetails","Custom Details","Answer area and safe-margin direction",{type:"textarea"})];
  if(builderName.includes("Educational Printable")) return [field("printableType","Printable Type",["Worksheet","Flashcards","Alphabet Activity","Number Activity","Matching Game","Tracing Page","Reward Chart","Routine Chart","Emotion Cards","Classroom Poster","Learning Game","Custom"],{required:true}),text("gradeLevel","Grade Level","Preschool, Grade 2..."),text("subject","Subject","Reading, math, science...",{required:true}),text("skillLevel","Skill Level","Beginner"),text("instructions","Instructions","Exact learner directions",{type:"textarea"}),text("itemCount","Number of Items","10",{inputMode:"numeric"}),field("pageSize","Page Size",["8.5 × 11 inches","A4","Custom"]),text("teacherNote","Teacher Note","Optional"),text("parentNote","Parent Note","Optional"),text("customDetails","Custom Details","Palette, answer area, safe margins",{type:"textarea"})];
  if(builderName.includes("School Supply")) return [field("product","School Product",["Composition Notebook Cover","Spiral Notebook Cover","Binder Cover","Planner Cover","Pencil Pouch Design","Water Bottle Wrap","School Name Labels","Bookmark","Button","Sticker Sheet","Pencil Wrap","Backpack Tag","Lunchbox Card","Folder Cover","Custom"],{required:true}),text("gradeLevel","Grade","Kindergarten"),text("theme","Theme","Back to school",{required:true}),text("namePlaceholder","Name Placeholder","[CHILD NAME]"),text("subject","School Subject","Optional"),field("palette","Palette",shared.palette),text("printSize","Print Size","Product-specific dimensions"),text("customDetails","Custom Details","Pattern, text treatment, safe margins",{type:"textarea"})];
  if(builderName.includes("Wallpaper")) return [field("format","Device Format",["Phone Portrait","Tablet Portrait","Tablet Landscape"],{required:true}),field("age","Child Age Group",["Baby","Toddler","Preschool Child","Young Child","Older Child","Tween","Teen"]),text("theme","Theme","Positive school energy",{required:true}),text("phrase","Exact Phrase","Optional"),field("palette","Palette",shared.palette),field("artStyle","Art Style",["Storybook","Kawaii","Soft 3D","Watercolor","Cartoon","Custom"]),text("customDetails","Custom Details","Text-safe area and small-screen direction",{type:"textarea"})];
  if(builderName.includes("Affirmation")) return [field("age","Age Group",["Preschool Child","Young Child","Older Child","Tween","Teen"]),text("cardCount","Number of Cards","12",{required:true,inputMode:"numeric"}),text("affirmation","Exact Affirmation Text","I am kind. I am capable.",{required:true,type:"textarea"}),field("tone","Tone",["Gentle","Confident","Faith-Based","Encouraging","Calming"]),field("palette","Palette",shared.palette),text("cardSize","Card Size","3 × 4 inches"),text("customDetails","Custom Details","Front/back layout and readability",{type:"textarea"})];
  if(builderName.includes("Bookmark")) return [field("age","Age Group",["Preschool Child","Young Child","Older Child","Tween","Teen"]),text("theme","Theme","Reading adventure",{required:true}),text("phrase","Exact Phrase","Reading takes you places",{required:true}),field("palette","Palette",shared.palette),text("bookmarkSize","Bookmark Size","2 × 6 inches"),field("holePunch","Hole Punch",["None","Top hole with tassel space"]),text("customDetails","Custom Details","Front/back and safe margins",{type:"textarea"})];
  if(builderName.includes("Mockup")) return [field("mockupType","Mockup Type",["Notebook Display","Binder Display","Planner Display","School Supply Flat Lay","Book Cover Display","Activity Pack Display","Printable Bundle Display","Tablet Display","Desk Display","Gift Box Presentation","Custom"],{required:true}),field("productStatus","Product Status",["Digital Product","Physical Product","Mockup Only"],{required:true}),text("productTitle","Product Title","Nyvera Kids Collection"),text("productCount","Number of Products","3",{inputMode:"numeric"}),field("lighting","Lighting",["Soft Daylight","Studio Lighting","Warm Home Lighting"]),text("customDetails","Presentation Details","Surface, props, branding space, camera angle",{type:"textarea"})];
  if(builderName.includes("Classroom")) return [...all.filter(x=>["age","skin","hairStyle","clothing","environment","lighting","palette","artStyle","customDetails"].includes(x.id)),text("gradeLevel","Grade Level","Grade 2",{required:true}),text("subject","Subject","Science",{required:true}),text("activity","Classroom Activity","Collaborative experiment"),text("studentCount","Number of Students","12",{inputMode:"numeric"}),field("textSpace","Text Space",["None","Top","Bottom","Side panel"])];
  if(builderName.includes("Family")||builderName.includes("Story Scene")) return [...all.filter(x=>common.includes(x.id)),text("peopleCount","Number of People","4",{inputMode:"numeric"}),text("relationships","Relationship Labels","Parent, child, sibling..."),text("activity","Scene Activity","Reading together")];
  return all.filter(x=>common.includes(x.id));
}
