import {dedupeNegative} from "./nyvera-prompts.js";

const list=value=>value.split("|").map(item=>item.trim()).filter(Boolean);
export const mockupTypes=list("Professional Sticker Pack|Sticker Sheet Display|Clear Acrylic Package|Clear Sleeve Package|Backing Card Display|Retail Hanging Package|Holographic Package|Luxury Gift Box|Sticker Pouch|Open Sticker Collection|Tablet Display|Laptop Display|Digital Download Display|Desk Flat Lay|Creative Workspace Display|Etsy Listing Mockup|Payhip Product Mockup|Online Store Product Card|Social Media Promotion|Bundle Preview|Gift Set Presentation|Custom Mockup");
export const productStatuses=list("Digital Sticker Pack|Printable Sticker Sheet|Physical Sticker Pack|Physical Sticker Sheet|Mockup Presentation Only");
export const mockupGroups=[
  {title:"Presentation Format",fields:[
    {id:"mockupTitle",label:"Mockup title",type:"text",required:true},
    {id:"mockupType",label:"Mockup type",options:mockupTypes,required:true},
    {id:"productStatus",label:"Product status",options:productStatuses,required:true},
    {id:"visibleProducts",label:"Number of visible products",type:"number",required:true},
    {id:"arrangement",label:"Visible product arrangement",options:list("Show Full Sticker Collection|Show Selected Sample Stickers|Show Sticker Sheet Only|Show Package and Loose Stickers"),required:true}
  ]},
  {title:"Package and Display",fields:[
    {id:"packageMaterial",label:"Package material",options:list("Clear Plastic|Frosted Plastic|Acrylic|Matte Paper|Glossy Paper|Holographic Material|Cardboard|Luxury Rigid Box|Fabric Pouch|No Package|Custom")},
    {id:"packageShape",label:"Package shape",options:list("Flat Sleeve|Standing Pouch|Rectangular Box|Square Box|Hanging Retail Pack|Backing Card|Open Gift Box|Digital Product Card|Custom")},
    {id:"packageFinish",label:"Package finish",options:list("Matte|Glossy|Holographic|Metallic|Iridescent|Soft-Touch|Transparent|Custom")}
  ]},
  {title:"Scene",fields:[
    {id:"surface",label:"Surface",options:list("White Marble|Warm Marble|Wood Desk|Pastel Desk|Glass Surface|Acrylic Pedestal|Fabric Surface|Paper Background|Digital Screen|Retail Shelf|Custom")},
    {id:"backgroundStyle",label:"Background style",options:list("Matching Sticker Theme|Clean White Studio|Luxury Retail|Colorful Creative Studio|Holographic Studio|Cozy Desk|Minimal Product Photography|Seller Workspace|Social Media Campaign|Custom")},
    {id:"lighting",label:"Lighting",options:list("Soft Daylight|Studio Lighting|Luxury Product Lighting|Bright Commercial Lighting|Warm Lifestyle Lighting|Holographic Glow|Softbox Lighting|Custom")},
    {id:"cameraAngle",label:"Camera angle",options:list("Front View|Three-Quarter View|Top-Down Flat Lay|Slight Overhead|Close-Up|Wide Product Scene|Eye-Level Retail View|Custom")}
  ]},
  {title:"Branding and Text Areas",fields:[
    {id:"brandingAreas",label:"Optional placeholders",type:"multi",options:list("Product Title|Brand Name|Sticker Count|Digital Download Label|Printable Sticker Sheet Label|Package Label|Price Area|Feature Badges|Shop Logo Area|Custom Text Area")},
    {id:"brandName",label:"Optional brand name",type:"text"},
    {id:"customText",label:"Optional custom text",type:"text"},
    {id:"customDetails",label:"Mockup custom details",type:"textarea"}
  ]}
];

const clean=value=>String(value??"").trim();
const safeText=value=>clean(value).replace(/\bNyvera\b/gi,"").replace(/\s{2,}/g," ").trim();
export const stickerCount=data=>{const direct=Number(data?.count);if(Number.isInteger(direct)&&direct>0)return direct;return ["phraseCount","iconCount","objectCount","decorativeCount","humanCount"].reduce((sum,key)=>sum+(Number(data?.[key])||0),0)};
export const inventorySummary=data=>[[data?.phraseCount,"phrases"],[data?.iconCount,"icons"],[data?.objectCount,"objects"],[data?.decorativeCount,"decorative designs"],[data?.humanCount,"human figures"]].filter(([count])=>Number(count)>0).map(([count,label])=>`${Number(count)} ${label}`).join(", ")||`${stickerCount(data)} distinct stickers`;
const statusFrom=value=>value==="Digital Download"?"Digital Sticker Pack":value==="Printable Sticker Sheet"?"Printable Sticker Sheet":value==="Physical Sticker Pack"?"Physical Sticker Pack":value==="Mockup Only"?"Mockup Presentation Only":"Physical Sticker Sheet";
const typeFrom=data=>data?.useType==="Digital Download"?"Digital Download Display":data?.productType?.includes("Sheet")?"Sticker Sheet Display":data?.productType?.includes("Pack")?"Professional Sticker Pack":"Open Sticker Collection";
export function inheritedMockupForm(data={},existing={}){const total=stickerCount(data),status=statusFrom(data.useType),digital=/Digital|Printable/.test(status);return {mockupId:existing.mockupId||globalThis.crypto?.randomUUID?.()||`mock_${Date.now()}`,mockupTitle:existing.mockupTitle||`${data.title||"Sticker Project"} Product Mockup`,mockupType:existing.mockupType||typeFrom(data),productStatus:existing.productStatus||status,visibleProducts:existing.visibleProducts||String(Math.min(total||1,6)),arrangement:existing.arrangement||(total<=6?"Show Full Sticker Collection":"Show Package and Loose Stickers"),packageMaterial:existing.packageMaterial||(digital?"No Package":"Clear Plastic"),packageShape:existing.packageShape||(digital?"Digital Product Card":"Flat Sleeve"),packageFinish:existing.packageFinish||data.finish||"Glossy",surface:existing.surface||(digital?"Digital Screen":"White Marble"),backgroundStyle:existing.backgroundStyle||"Matching Sticker Theme",lighting:existing.lighting||(data.finish==="Holographic"?"Holographic Glow":"Studio Lighting"),cameraAngle:existing.cameraAngle||(digital?"Front View":"Three-Quarter View"),brandingAreas:Array.isArray(existing.brandingAreas)?existing.brandingAreas:[],brandName:existing.brandName||"",customText:existing.customText||"",customDetails:existing.customDetails||""};}

export function validateMockup(stickerData,form){const errors=[],total=stickerCount(stickerData),visible=Number(form.visibleProducts);if(!form.mockupTitle?.trim())errors.push("Add a mockup title.");if(!mockupTypes.includes(form.mockupType))errors.push("Choose a mockup type.");if(!productStatuses.includes(form.productStatus))errors.push("Choose a product status.");if(!total)errors.push("The sticker project needs a valid exact count before creating a mockup.");if(!Number.isInteger(visible)||visible<1)errors.push("Visible products must be a whole number of at least 1.");if(form.arrangement==="Show Full Sticker Collection"&&visible!==total)errors.push(`Show Full Sticker Collection requires exactly ${total} visible stickers.`);if(form.arrangement==="Show Selected Sample Stickers"&&visible>=total)errors.push("A selected sample must show fewer stickers than the exact collection total.");if(visible>total&&total)errors.push(`Visible products cannot exceed the exact total of ${total}.`);return [...new Set(errors)]}

const statusDirection=status=>status==="Digital Sticker Pack"?"Present this explicitly as a digital download; make no shipping or physical-box claim":status==="Printable Sticker Sheet"?"Present this explicitly as a printable file; do not imply pre-cut physical stickers or shipping":status==="Physical Sticker Pack"?"Present this as a physical sticker pack without shipping promises":status==="Physical Sticker Sheet"?"Present this as a physical sticker sheet without unsupported shipping promises":"Treat this as a visual presentation concept only, with no delivery or shipping claims";
const arrangementDirection=(form,total)=>form.arrangement==="Show Full Sticker Collection"?`Display the exact ${total}-piece sticker collection, with every sticker distinct and visible`:form.arrangement==="Show Selected Sample Stickers"?`Show exactly ${form.visibleProducts} sample stickers while clearly stating that the represented product contains an exact total of ${total} stickers; the visible samples are not the total`:form.arrangement==="Show Sticker Sheet Only"?`Show one complete sticker sheet representing the exact ${total}-piece collection without adding or removing stickers`:`Show the package with exactly ${form.visibleProducts} loose sample stickers and clearly state that the package represents an exact total of ${total} stickers`;
export function generateMockup(stickerData,stickerResult,form){
  const errors=validateMockup(stickerData,form);if(errors.length)return {errors,prompt:"",negative:""};
  const total=stickerCount(stickerData),brand=safeText(form.brandName),custom=safeText(form.customText),areas=(form.brandingAreas||[]).filter(Boolean),branding=areas.length?`Reserve optional, clean placeholder areas for ${areas.join(", ")}${areas.includes("Brand Name")&&brand?`; use only the supplied brand name “${brand}”`:""}${areas.includes("Custom Text Area")&&custom?`; use only the supplied custom text “${custom}”`:""}. Do not invent any other branding or text.`:`Keep the entire presentation completely unbranded with no logo, wordmark, emblem, monogram, or watermark.`;
  const digital=/Digital|Printable/.test(form.productStatus),packageDirection=form.packageMaterial==="No Package"?`Use ${form.packageShape} presentation with no physical package`:digital?`Show the ${form.packageShape.toLowerCase()}, ${form.packageMaterial.toLowerCase()}, and ${form.packageFinish.toLowerCase()} finish only as a decorative on-screen presentation concept; no physical package is included`:`Use a ${form.packageShape.toLowerCase()} made from ${form.packageMaterial.toLowerCase()} with a ${form.packageFinish.toLowerCase()} finish`;
  const inherited=[stickerData.style&&`${stickerData.style} sticker style`,stickerData.palette&&`${stickerData.palette} palette`,stickerData.finish&&`${stickerData.finish} sticker finish`,stickerData.border&&`${stickerData.border.toLowerCase()}`,stickerData.background&&`${stickerData.background.toLowerCase()}`].filter(Boolean).join(", ");
  const sourcePrompt=safeText(stickerResult?.prompt),prompt=[`Create a professional ${form.mockupType.toLowerCase()} titled “${safeText(form.mockupTitle)}” for the finished sticker project “${safeText(stickerData.title)}”.`,`The product status is ${form.productStatus}. ${statusDirection(form.productStatus)}.`,`${arrangementDirection(form,total)}.`,`The exact inventory is ${inventorySummary(stickerData)}. Preserve every category and do not invent extra stickers.`,`Match the original ${safeText(stickerData.theme)||"cohesive"} theme and ${inherited||"original sticker styling"}.`,sourcePrompt?`Use this completed sticker-art direction as the exact visual source: ${sourcePrompt}.`:"",`${packageDirection}.`,`Stage the product on ${form.surface.toLowerCase()} against ${form.backgroundStyle.toLowerCase()}, using ${form.lighting.toLowerCase()} and a ${form.cameraAngle.toLowerCase()} camera angle.`,`Keep sticker artwork fully visible, crisp, separated, countable, and consistent with the completed source prompt.`,branding,`Use polished commercial product photography, realistic structure, controlled props that directly match the sticker theme, clean spacing, and listing-ready clarity.`,safeText(form.customDetails)].filter(Boolean).join(" ").replace(/\s+/g," ").trim();
  const negative=dedupeNegative(stickerResult?.negative,stickerData.negative,"incorrect sticker count, missing stickers, duplicate stickers, overlapping stickers, cropped products, warped packaging, unreadable labels, misspelled text, broken package structure, unrelated products, cluttered composition, low-resolution artwork, blurry stickers, inconsistent sticker style, muddy colors",/Digital|Printable/.test(form.productStatus)?"fake shipping claims, physical shipping promises":"","logos, brand names, wordmarks, signatures, watermarks, monograms, standalone letter N symbols");
  return {errors:[],prompt,negative,summary:{stickerTitle:stickerData.title,mockupTitle:form.mockupTitle,mockupType:form.mockupType,productStatus:form.productStatus,exactCount:total,inventory:inventorySummary(stickerData)}};
}

export function styleMockup(stickerData,form){const text=`${stickerData.theme} ${stickerData.style} ${stickerData.finish}`.toLowerCase(),digital=/Digital|Printable/.test(form.productStatus),faith=/faith|church|gospel/.test(text),cozy=/cozy|reading|home/.test(text),holo=/holographic|iridescent/.test(text),luxury=/luxury|elegant|premium/.test(text);return {...form,mockupType:digital?"Digital Download Display":luxury?"Luxury Gift Box":holo?"Holographic Package":"Professional Sticker Pack",packageMaterial:digital?"No Package":luxury?"Luxury Rigid Box":holo?"Holographic Material":"Clear Plastic",packageShape:digital?"Digital Product Card":luxury?"Open Gift Box":"Flat Sleeve",packageFinish:holo?"Holographic":luxury?"Soft-Touch":stickerData.finish||"Glossy",surface:digital?"Digital Screen":cozy?"Wood Desk":luxury?"Acrylic Pedestal":"White Marble",backgroundStyle:faith?"Minimal Product Photography":cozy?"Cozy Desk":holo?"Holographic Studio":luxury?"Luxury Retail":"Matching Sticker Theme",lighting:faith?"Soft Daylight":cozy?"Warm Lifestyle Lighting":holo?"Holographic Glow":luxury?"Luxury Product Lighting":"Studio Lighting",cameraAngle:digital?"Front View":cozy?"Top-Down Flat Lay":"Three-Quarter View"};}
export function surpriseMockup(stickerData,form,seed=Date.now()){const compatible=/Digital|Printable/.test(form.productStatus)?[["Tablet Display","Digital Screen","Front View"],["Online Store Product Card","Digital Screen","Front View"],["Etsy Listing Mockup","Paper Background","Slight Overhead"]]:[["Desk Flat Lay","Wood Desk","Top-Down Flat Lay"],["Clear Sleeve Package","White Marble","Three-Quarter View"],["Backing Card Display","Acrylic Pedestal","Front View"],["Creative Workspace Display","Pastel Desk","Slight Overhead"]],choice=compatible[Math.abs(Number(seed))%compatible.length],styled=styleMockup(stickerData,form);return {...styled,mockupType:choice[0],surface:choice[1],cameraAngle:choice[2]}}
