import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const app=fs.readFileSync(new URL("../js/app.js",import.meta.url),"utf8"),css=fs.readFileSync(new URL("../css/nyvera.css",import.meta.url),"utf8"),sw=fs.readFileSync(new URL("../service-worker.js",import.meta.url),"utf8"),build=fs.readFileSync(new URL("../scripts/build.ps1",import.meta.url),"utf8"),html=fs.readFileSync(new URL("../index.html",import.meta.url),"utf8"),manifest=fs.readFileSync(new URL("../manifest.webmanifest",import.meta.url),"utf8");
test("Character result directly renders the optional Adult product card and linked variants",()=>{for(const text of ["function adultProductOffer","state.studio===\"character\"\\?adultProductOffer\\(\\)","s.id===\"character\"\\?adultProductOffer\\(\\)","Create a Product From This Character","Turn this finished adult character into a professional fashion, branding, publishing, merchandise, collectible, event, or product design.","create-adult-product","skip-adult-product","data-open-adult-product"])assert.match(app,new RegExp(text))});
test("Adult catalog, filters, favorites, builder, proposals, results, and return path are wired",()=>{for(const text of ["renderAdultProductCatalog","data-adult-product-search","data-adult-product-category","data-adult-product-classification","Favorite Format","Recently used","Clear Filters","renderAdultProductBuilder","Style My Product","Surprise My Product","Image-generation tools may not render visible text perfectly. Final text may need to be added in a design editor.","Your Adult Product Prompt Is Ready","Copy Product Negative Prompt","Save Linked Product","Duplicate Only This Product","Return to Original Character Result","Switch Studio"])assert.match(app,new RegExp(text))});
test("Adult workflow reuses responsive product layouts and premium Character styling",()=>{assert.match(css,/\.adult-product-offer/);assert.match(css,/\.adult-product-card/);assert.match(css,/\.product-stage-grid/);assert.match(css,/@media\(max-width:430px\).*\.product-actions/s);assert.match(css,/overflow-wrap:anywhere/)});
test("production build and app shell include the Adult module with a fresh cache",()=>{assert.match(build,/nyvera-adult-products\.js/g);assert.match(sw,/nyvera-adult-products\.js\?v=1\.13\.0/);assert.match(sw,/v1\.19\.0-persistent-iheart-reveal/);assert.match(html,/js\/app\.js\?v=1\.19\.0/)});
test("Adult add-on surfaces use explicit readable foreground colors",()=>{assert.match(css,/\.adult-product-card,\.adult-product-screen \.product-stage[^\{]*\{color:#281526\}/);assert.match(css,/\.adult-product-screen \.product-stage input[^\{]*\{color:#fffaf0;background:#29142d/);assert.match(css,/\.adult-product-screen \.product-stage \.choice span\{color:#31192d;background:#fffaf0/)});
test("copy fallback never opens a blocking dialog",()=>{assert.match(app,/function legacyCopyText/);assert.match(app,/Copy was blocked by this browser\. Use Download TXT instead/);assert.doesNotMatch(app,/showDialog\("Copy this text"/)});
test("Phone install is visible and supports native prompt plus platform instructions",()=>{for(const text of ["Install on This Phone","Install Nyvera on This Phone","beforeinstallprompt","appinstalled","data-install-offline","Add to Home Screen","Open as Web App","window.isSecureContext"])assert.match(app,new RegExp(text));assert.match(css,/\.offline-install-panel/);for(const icon of ["nyvera-mark-192.png","nyvera-mark-512.png"])assert.match(manifest,new RegExp(icon.replace(".","\\.")));assert.match(html,/apple-touch-icon/)});
