import test from "node:test";
import assert from "node:assert/strict";
import {adultProductCategories,adultProducts,adultProductDuplicateReport,adultProductClassifications,adultProductByName,adultProductStages,adultTradingCardFields,inheritAdultProductForm,validateAdultProduct,generateAdultProduct,styleAdultProduct,surpriseAdultProduct} from "../js/nyvera-adult-products.js";

const source={title:"Avery Executive Portrait",age:"Mature Adult",presentation:"Woman",role:"Creative Director",occupation:"Brand Strategist",height:"Tall",bodyType:"Curvy",build:"Realistic Adult Proportions",skin:"Deep Brown",undertone:"Warm Golden",complexion:"Natural",face:"Oval",facialFeatures:"High cheekbones",eyes:"Almond",eyeColor:"Dark Brown",brows:"Defined",lashes:"Natural",hairTexture:"Coily",hairStyle:"Elegant Updo",hairLength:"Shoulder Length",hairColor:"Black",hairDetails:"Gold cuffs",makeup:"Soft Glam",lipFinish:"Satin",nails:"Burgundy",clothing:"Nyvera Luxury Clothing Line",outfit:"Tailored ivory pantsuit",tops:"Silk blouse",bottoms:"Wide-leg trousers",fabric:"Silk and wool",pattern:"Solid",fit:"Tailored",luxuryOutfit:"Nyvera Luxury Clothing Line",shoes:"Gold heels",accessories:["Structured handbag"],jewelry:["Gold earrings"],expression:"Confident",pose:"Three-quarter standing pose",activity:"Presenting a portfolio",energy:"Visionary",environment:"Editorial studio",lighting:"Soft directional studio light",timeOfDay:"Evening",sceneMood:"Refined",palette:"Plum, champagne gold, warm ivory",artStyle:"Luxury-realistic editorial",composition:"Three-quarter portrait",quality:"Commercial campaign quality",outputFormat:"Portrait PNG",customDetails:"Preserve her beauty mark"};
const project={id:"character-1",title:"Avery Executive Portrait",builderType:"Full Character Builder"};
const result={prompt:"A completed adult creative director in a tailored ivory pantsuit.",negative:"weapons, children, logos"};
const setup=name=>{const product=adultProductByName(name),form=inheritAdultProductForm(source,product);if(form.sides==="Front and Back")form.backCardText="Lead with vision.";return {product,form}};

test("Adult catalog contains ten organized categories and 299 unique accepted formats",()=>{assert.equal(Object.keys(adultProductCategories).length,10);assert.equal(adultProducts.length,299);assert.equal(new Set(adultProducts.map(item=>item.name.toLowerCase().replace(/[^a-z0-9]/g,""))).size,299);assert.equal(adultProductDuplicateReport.length,4);for(const name of ["Editorial Magazine Cover","Business Branding Portrait","Book Cover","Canvas Wall Art","T-Shirt Design","YouTube Thumbnail","Character Trading Card","Cosmetic Package","VIP Pass","Luxury Editorial"])assert.ok(adultProductByName(name),name)});
test("Adult product controls contain no duplicate options",()=>{for(const stage of adultProductStages){for(const field of stage.fields){if(!field.options)continue;const keys=field.options.map(option=>option.toLocaleLowerCase().replace(/[^a-z0-9]/g,""));assert.equal(new Set(keys).size,keys.length,`${stage.title}: ${field.label}`)}}for(const field of adultTradingCardFields){if(!field.options)continue;const keys=field.options.map(option=>option.toLocaleLowerCase().replace(/[^a-z0-9]/g,""));assert.equal(new Set(keys).size,keys.length,field.label)}});
test("Adult product builder is exactly three compact stages with collectible controls",()=>{assert.deepEqual(adultProductStages.map(stage=>stage.title),["Stage 1 — Product Format","Stage 2 — Text and Content","Stage 3 — Visual Presentation"]);assert.ok(adultTradingCardFields.some(field=>field.id==="frontContent"));assert.ok(adultTradingCardFields.some(field=>field.id==="backContent"));assert.ok(adultTradingCardFields.some(field=>field.id==="positiveTraits"));assert.deepEqual(adultProductClassifications,["Digital Download","Printable Product","Physical Product Design","Product Mockup Only"])});
test("all Adult builder families can create a linked product",()=>{const builders=["Full Character Builder","Quick Character Builder","Face Builder","Hair Builder","Fashion Builder","Portrait Builder","Professional Character Builder","Editorial Character Builder","Couple Builder","Adult Family Builder","Adult Group Builder","Avatar Builder","Character Sheet Builder","Style Me","Surprise Me","Character Templates"];for(const [index,builderType] of builders.entries()){const {product,form}=setup(index%2?"Professional Headshot":"Editorial Magazine Cover"),generated=generateAdultProduct({...project,builderType},source,result,product,form);assert.deepEqual(generated.errors,[],builderType);assert.match(generated.prompt,/same adult character/i);assert.match(generated.prompt,/Original Character Project/)}});
test("source identity, fashion, scene, and commercial direction transfer automatically",()=>{const {product,form}=setup("Fashion Campaign Poster"),generated=generateAdultProduct(project,source,result,product,form);for(const detail of ["Mature Adult","Woman","Creative Director","Brand Strategist","Deep Brown","Warm Golden","High cheekbones","Almond","Elegant Updo","Tailored ivory pantsuit","Gold heels","Structured handbag","Editorial studio","Soft directional studio light","Plum, champagne gold, warm ivory","Luxury-realistic editorial","Commercial campaign quality"])assert.match(generated.prompt,new RegExp(detail,"i"),detail)});
test("Adult trading cards support explicit coordinated front and back content",()=>{const {product,form}=setup("Double-Sided Character Trading Card");form.frontContent=["Character Name","Character Portrait","Role","Card Number"];form.backContent=["Short Biography","Profession","Strengths","Collection Information"];form.cardNumber="A-021";form.positiveTraits=["Leadership","Creativity","Vision"];const generated=generateAdultProduct(project,source,result,product,form);assert.deepEqual(generated.errors,[]);assert.match(generated.prompt,/coordinated front and back/i);assert.match(generated.prompt,/character name, character portrait, role, card number/i);assert.match(generated.prompt,/short biography, profession, strengths, collection information/i);assert.match(generated.prompt,/Leadership, Creativity, Vision/);assert.match(generated.prompt,/Never add attack power, weapons, battle ratings/i)});
test("front-only collectible No Visible Text suppresses all entered text",()=>{const {product,form}=setup("Character Trading Card");form.frontContent=["Character Portrait","No Visible Text"];form.characterName="Avery";const generated=generateAdultProduct(project,source,result,product,form);assert.deepEqual(generated.errors,[]);assert.match(generated.prompt,/Place no visible text anywhere/);assert.doesNotMatch(generated.prompt,/character name: “Avery”/i);form.frontContent.push("Character Name");assert.match(validateAdultProduct(source,product,form).join(" "),/card front conflicts/i)});
test("exact visible text preserves spelling, capitalization, and punctuation",()=>{const {product,form}=setup("Speaker Promo Card");form.exactPhrase="Lead Boldly — Build Beautifully!";form.businessName="Avery & Co.";form.date="October 18, 2026";const generated=generateAdultProduct(project,source,result,product,form);assert.match(generated.prompt,/Lead Boldly — Build Beautifully!/);assert.match(generated.prompt,/Avery & Co\./);assert.match(generated.prompt,/October 18, 2026/);assert.match(generated.prompt,/Render all visible text exactly as provided/)});
test("luxury clothing is brand-neutral and empty branding stays unbranded",()=>{const {product,form}=setup("Luxury Editorial"),generated=generateAdultProduct({...project,title:"Nyvera Character Studio"},{...source,title:"Nyvera",customDetails:"Nyvera Luxury Clothing Line"},{prompt:"Nyvera Luxury Clothing Line editorial",negative:""},product,form);assert.doesNotMatch(generated.prompt,/Nyvera/i);assert.match(generated.prompt,/designer-inspired luxury fashion/i);assert.match(generated.prompt,/completely unbranded/i)});
test("four product classifications cannot make conflicting fulfillment claims",()=>{const {product,form}=setup("Custom Fashion Product");for(const classification of adultProductClassifications){const generated=generateAdultProduct(project,source,result,product,{...form,classification});assert.deepEqual(generated.errors,[]);if(classification==="Digital Download")assert.match(generated.prompt,/digital download.*no shipping/i);if(classification==="Printable Product")assert.match(generated.prompt,/printable file.*print-safe/i);if(classification==="Physical Product Design")assert.match(generated.prompt,/physical production.*without promising fulfillment/i);if(classification==="Product Mockup Only")assert.match(generated.prompt,/presentation mockup only/i)}});
test("category-specific business, publishing, merchandise, and packaging protections are generated",()=>{for(const [name,pattern] of [["Business Card",/never invent phone numbers/i],["Paperback Cover",/never fabricate an ISBN/i],["T-Shirt Design",/flat artwork, product mockup, and print-placement preview/i],["Cosmetic Package",/exactly 1 product/i]]){const {product,form}=setup(name),generated=generateAdultProduct(project,source,result,product,form);assert.match(generated.prompt,pattern,name)}});
test("Style and Surprise propose complete adult-only product setups without changing identity",()=>{const {product,form}=setup("Character Trading Card"),styled=styleAdultProduct(source,product,form),first=surpriseAdultProduct(source,product,form,0),second=surpriseAdultProduct(source,product,form,1);assert.equal(styled.productId,form.productId);assert.ok(styled.layout);assert.ok(styled.characterView);assert.ok(styled.finish.length);assert.equal(first.form.productId,form.productId);assert.equal(second.form.productId,form.productId);assert.notEqual(first.product.name,second.product.name);assert.doesNotMatch(`${first.product.name} ${second.product.name}`,/Baby|Kids|Child/i)});
test("negative prompt is deduplicated and blocks child, identity, violence, branding, and product errors",()=>{const {product,form}=setup("Character Trading Card"),generated=generateAdultProduct(project,{...source,negative:["weapons","children"]},{...result,negative:"weapons, logos"},product,form),parts=generated.negative.split(",").map(item=>item.trim().toLowerCase());assert.equal(parts.length,new Set(parts).size);for(const term of ["children","teenagers","childlike body proportions","changed facial identity","duplicate character","weapons","incorrect product count","logos","standalone letter n symbols"])assert.ok(parts.includes(term),term)});

test("representative products from every category generate complete clean prompts",()=>{const samples=["Editorial Magazine Cover","Fashion Lookbook Page","Fashion Campaign Poster","Jewelry Showcase Card","Business Branding Portrait","Business Card","Speaker Promo Card","LinkedIn Banner","Book Cover","Journal Cover","Planner Cover","Bookmark","Canvas Wall Art","Framed Art Print","Faith Wall Art","T-Shirt Design","Tote Bag Design","Mug Design","Phone Case Design","Phone Wallpaper","Social Media Post","YouTube Thumbnail","Website Hero Banner","Character Trading Card","Double-Sided Character Trading Card","Collector Card Pack","Cosmetic Package","Luxury Gift Box","Doll Box","Payhip Product Mockup","Event Invitation","Event Flyer","VIP Pass","Church Program Cover","Luxury Editorial","Gala Poster","Signature Collection","Collector’s Edition Portfolio"];for(const name of samples){const product=adultProductByName(name);if(!product)continue;const {form}=setup(name),generated=generateAdultProduct(project,source,result,product,form);assert.deepEqual(generated.errors,[],name);assert.ok(generated.prompt.length>300,name);assert.doesNotMatch(generated.prompt,/\bundefined\b|\bnull\b|\[object Object\]|\bn\/a\b/i,name);assert.doesNotMatch(generated.prompt,/Nyvera/i,name)}});
